In [3]:
pip! install matplotlib

Note: you may need to restart the kernel to use updated packages.

ERROR: unknown command "!"

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
#creating dictionary
Dict={
    'id': [1,2,3,4,5],
    'name': ["Alice", "Bob", "Charlie", "David", "Eve"],
    'age': [25, 30, 35, 40, 45],
    'marks': [85, 90, None, 80, 75],
    'gender': ['f', 'm', 'm', 'm', 'f']
}

In [35]:
df = pd.DataFrame(Dict)

In [36]:
df

   id     name  age  marks gender
0   1    Alice   25   85.0      f
1   2      Bob   30   90.0      m
2   3  Charlie   35    NaN      m
3   4    David   40   80.0      m
4   5      Eve   45   75.0      f

In [37]:
df.head()

   id     name  age  marks gender
0   1    Alice   25   85.0      f
1   2      Bob   30   90.0      m
2   3  Charlie   35    NaN      m
3   4    David   40   80.0      m
4   5      Eve   45   75.0      f

In [38]:
df.tail()

   id     name  age  marks gender
0   1    Alice   25   85.0      f
1   2      Bob   30   90.0      m
2   3  Charlie   35    NaN      m
3   4    David   40   80.0      m
4   5      Eve   45   75.0      f

In [39]:
df[['name']]

      name
0    Alice
1      Bob
2  Charlie
3    David
4      Eve

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      5 non-null      int64
 1   name    5 non-null      str
 2   age     5 non-null      int64
 3   marks   4 non-null      float64
 4   gender  5 non-null      str
dtypes: float64(1), int64(2), str(2)
memory usage: 332.0 bytes

In [41]:
df_re=df

In [42]:
df_re

   id     name  age  marks gender
0   1    Alice   25   85.0      f
1   2      Bob   30   90.0      m
2   3  Charlie   35    NaN      m
3   4    David   40   80.0      m
4   5      Eve   45   75.0      f

In [43]:
df_re.dropna()

   id   name  age  marks gender
0   1  Alice   25   85.0      f
1   2    Bob   30   90.0      m
3   4  David   40   80.0      m
4   5    Eve   45   75.0      f

In [44]:
df_re['marks'].mean()

np.float64(82.5)

In [45]:
df_re['marks'].median()

np.float64(82.5)

In [46]:
df_re['marks']=df_re['marks'].fillna(df_re['marks'].mean())

In [47]:
df_re

   id     name  age  marks gender
0   1    Alice   25   85.0      f
1   2      Bob   30   90.0      m
2   3  Charlie   35   82.5      m
3   4    David   40   80.0      m
4   5      Eve   45   75.0      f

In [48]:
df_re.isnull().sum()

id        0
name      0
age       0
marks     0
gender    0
dtype: int64

In [49]:
df_re=pd.get_dummies(df["gender"],prefix="gender").astype("int64")
print (df_re)

   gender_f  gender_m
0         1         0
1         0         1
2         0         1
3         0         1
4         1         0

In [ ]:
df_new_gen.drop(columns=['name'], inplace=True)

NameError: name 'df_new_gen' is not defined